### ISSUE TITLE
Reference Documentation

### ISSUE THREAD

**Issue by jnitin** [is-centre/ue4-alab-control-vr-421#1]
Hi

Please let me know if there is any reference documentation available for this project  like high level flow , architecture etc . 

Thanks

**Comment by extall** [comment]
We are preparing a research publication with relevant information. Other than that, no, not at the moment.

**Comment by jnitin** [comment]
Thanks for information . Hope research publication also will be available at git-hub.

In the meantime  , is it possible to share any  links which can be  referred to  build such kind of Digital Twin mainly how CAD model is linked to unreal  / unity engine and real time rendering of live data can be done . 

Thanks !

**Comment by extall** [comment]
The publication will be in an open access journal, so you will be able to read it.
Regarding communication, etc., maybe you can consider our earlier paper where the real-time aspect is discussed: https://jcomss.fesb.unist.hr/index.php/jcomss/article/view/410
You can find our other publications on this topic also.

**Comment by extall** [comment]
Also, consider this paper which documents a follow up effort to our developments in this repository: https://ieeexplore.ieee.org/document/9163557

If you cannot access it, please contact me directly (send an email to aleksei.tepljakov at taltech.ee) and I will share it with you.
